---
title: "Group Project"
format:
  html:
    toc: true
    toc-location: right   # or right
    theme: yeti
---
Each group will receive a dataset from a nektonic monitoring program in Louisiana consisting of monthly trawl or gill net catches from various sites (each unique combination of latitude and longitude = a site) within five main basins/watersheds. The group project involves creating population models and conducting community analysis using the assigned datasets. Please organize the code and a brief write-up of the results as a report-style document (Quarto PDF or HTML file), and use this document to present a 15-minute PowerPoint presentation. 

## 1. Population Models 

1.1 – Use a discrete density-dependent and -independent population model to assess the population growth dynamics of any three species within the 10 most abundant species. What can you infer from both models (Modeli | Speciesi)? For each species, what is the most proper model to assess their growth? Why? 

1.2 – Based on the selected models, how does lambda change across time? 

1.3 – Starting with the average abundance in 2000, perform a simulation (N = 100 replicates) of population growth using the growth variability based on the abundance values from start to 1999 (i.e., use 100 samples of lambda from 1980 to 1999’s frequency distribution to project population beyond 2000). How many times are the real abundance values intercepted by the uncertainty bounds of the simulation (i.e., values within the 95% confidence intervals)? Briefly discussed the performance of the models and potential reasons for the results. 

## 2. Community Analysis 

2.1 – Does the sampling assigned to your group reach the asymptote of the species accumulation curve? Discuss results. 

2.2 - Using the species that composed 75% of the abundance of species within the nektonic community, assess the annual trends of alpha and beta diversity, and the inverse Simpson diversity index. 

2.3 – Using a community trajectory analysis, assess the annual stability of the fish community across the sites from the assigned basin and gear type. Describe and discuss the main results 